//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinPosMgr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinPosMgr.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid commandline arguments!
        ///Now running in GUI mode..
        /// </summary>
        internal static string cliArg_error_invalidArg {
            get {
                return ResourceManager.GetString("cliArg_error_invalidArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gui.
        /// </summary>
        internal static string cliArg_opMode_gui {
            get {
                return ResourceManager.GetString("cliArg_opMode_gui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to run.
        /// </summary>
        internal static string cliArg_opMode_run {
            get {
                return ResourceManager.GetString("cliArg_opMode_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string editJob_button_test {
            get {
                return ResourceManager.GetString("editJob_button_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string editJob_checkBox_enabled {
            get {
                return ResourceManager.GetString("editJob_checkBox_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoMove.
        /// </summary>
        internal static string editJob_checkBox_noMove {
            get {
                return ResourceManager.GetString("editJob_checkBox_noMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoSize.
        /// </summary>
        internal static string editJob_checkBox_noSize {
            get {
                return ResourceManager.GetString("editJob_checkBox_noSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoZOrder.
        /// </summary>
        internal static string editJob_checkBox_noZOrder {
            get {
                return ResourceManager.GetString("editJob_checkBox_noZOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string editJob_groupBox_flags {
            get {
                return ResourceManager.GetString("editJob_groupBox_flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string editJob_groupBox_position {
            get {
                return ResourceManager.GetString("editJob_groupBox_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Process.
        /// </summary>
        internal static string editJob_groupBox_searchProc {
            get {
                return ResourceManager.GetString("editJob_groupBox_searchProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string editJob_groupBox_size {
            get {
                return ResourceManager.GetString("editJob_groupBox_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Job.
        /// </summary>
        internal static string editJob_title_edit {
            get {
                return ResourceManager.GetString("editJob_title_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        internal static string editJob_title_new {
            get {
                return ResourceManager.GetString("editJob_title_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid position.
        ///Value remains unchanged..
        /// </summary>
        internal static string editJob_warning_invalidPosition {
            get {
                return ResourceManager.GetString("editJob_warning_invalidPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid size.
        ///Value remains unchanged..
        /// </summary>
        internal static string editJob_warning_invalidSize {
            get {
                return ResourceManager.GetString("editJob_warning_invalidSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Z position.
        ///Value remains unchanged..
        /// </summary>
        internal static string editJob_warning_invalidZPosition {
            get {
                return ResourceManager.GetString("editJob_warning_invalidZPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string gApply {
            get {
                return ResourceManager.GetString("gApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position Manager.
        /// </summary>
        internal static string gAppName {
            get {
                return ResourceManager.GetString("gAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinPosMgr.
        /// </summary>
        internal static string gAppName_abbr {
            get {
                return ResourceManager.GetString("gAppName_abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string gCancel {
            get {
                return ResourceManager.GetString("gCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string gError {
            get {
                return ResourceManager.GetString("gError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error!.
        /// </summary>
        internal static string gFatalError {
            get {
                return ResourceManager.GetString("gFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string gInfo {
            get {
                return ResourceManager.GetString("gInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string gInformation {
            get {
                return ResourceManager.GetString("gInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string gNo {
            get {
                return ResourceManager.GetString("gNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string gOK {
            get {
                return ResourceManager.GetString("gOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string gWarning {
            get {
                return ResourceManager.GetString("gWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string gYes {
            get {
                return ResourceManager.GetString("gYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the selected job permanently?.
        /// </summary>
        internal static string mainForm_deleteJobDialog {
            get {
                return ResourceManager.GetString("mainForm_deleteJobDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string mainForm_toolStripButton_job_add_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripButton_job_add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string mainForm_toolStripButton_job_edit_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripButton_job_edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string mainForm_toolStripButton_job_reload_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripButton_job_reload_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string mainForm_toolStripButton_job_remove_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripButton_job_remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string mainForm_toolStripButton_job_run_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripButton_job_run_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string mainForm_toolStripMenuItem_file_exit_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripMenuItem_file_exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string mainForm_toolStripMenuItem_file_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripMenuItem_file_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string mainForm_toolStripMenuItem_help_about_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripMenuItem_help_about_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repo (www).
        /// </summary>
        internal static string mainForm_toolStripMenuItem_help_gitHubPage_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripMenuItem_help_gitHubPage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string mainForm_toolStripMenuItem_help_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripMenuItem_help_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string mainForm_toolStripMenuItem_options_settings_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripMenuItem_options_settings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string mainForm_toolStripMenuItem_options_Text {
            get {
                return ResourceManager.GetString("mainForm_toolStripMenuItem_options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process not found:.
        /// </summary>
        internal static string nsApplication_Job_Run_Warning_ProcNotFound {
            get {
                return ResourceManager.GetString("nsApplication_Job_Run_Warning_ProcNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid section.
        /// </summary>
        internal static string nsApplication_JobsFile_Get_ErrorInvalidSection {
            get {
                return ResourceManager.GetString("nsApplication_JobsFile_Get_ErrorInvalidSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse job in section.
        /// </summary>
        internal static string nsApplication_JobsFile_Get_ErrorParse {
            get {
                return ResourceManager.GetString("nsApplication_JobsFile_Get_ErrorParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Mode.
        /// </summary>
        internal static string settings_general_defaultOpMode {
            get {
                return ResourceManager.GetString("settings_general_defaultOpMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs file.
        /// </summary>
        internal static string settings_general_jobsFile {
            get {
                return ResourceManager.GetString("settings_general_jobsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reporting in run mode.
        /// </summary>
        internal static string settings_general_opModeRunErrRep {
            get {
                return ResourceManager.GetString("settings_general_opModeRunErrRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string settings_tab_general {
            get {
                return ResourceManager.GetString("settings_tab_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_titel {
            get {
                return ResourceManager.GetString("settings_titel", resourceCulture);
            }
        }
    }
}
